### PR TITLE
Add one-click deploy to docs

### PR DESCRIPTION
**Pull request by jbgh**
@DarthSim I saw your comment here: https://github.com/imgproxy/imgproxy/issues/1211#issuecomment-1766680977 and thought that we could help provide a cool one-click deploy experience for imgproxy users.

We’ve made the default [one-click deployment](https://app.trydome.io/signup?package=imgproxy) 0.75 CPU cores + 1GB of RAM and it seems to be working fine but could up it to the 2 CPU cores that you recommended for the reasons you stated (multiple global mutexes + round robin LBs potentially sending another job to an already busy instance).

Dome is pretty flexible so it’s possible for users to configure high CPU core counts and still stick with 1GB of RAM or you could also go horizontal with as many 2 CPU cores + 256MB RAM replicas as needed if for example the use case is high concurrency processing of relatively small sized images.  Let me know if you have any additional thoughts.  Thanks.

### CODE REVIEW

**Comment by DarthSim** [comment]
Hi @jbgh!

We have a documentation page about installation ways: https://github.com/imgproxy/imgproxy/blob/master/docs/installation.md. It's better to add the button there rather than to  README

**Comment by jbgh** [comment]
Hi @DarthSim thanks for the feedback!  I've moved the button to your docs and removed it from the readme.

**Comment by jbgh** [comment]
@DarthSim bumping for review.  Let me know if you have any other thoughts/feedback.  Thanks!

**Comment by DarthSim** [comment]
We moved documentation source code to https://github.com/imgproxy/imgproxy-docs. I already added a button for Dome: https://docs.imgproxy.net/installation#dome

**Comment by jbgh** [comment]
Thanks @DarthSim for the merge!  Reach out to jay@trydome.io if you have any requests or issues.

**Comment by jbgh** [comment]
@DarthSim looks like the link in the docs is incorrect.  The link on `Dome` in the docs is pointing to heroku.  This is the correct link:

https://app.trydome.io/signup?package=imgproxy

**Comment by DarthSim** [comment]
My bad. Fixed

**Pull request closed without merging**
