### PR TITLE
Optionally return rel="canonical" header

### PR DESCRIPTION
**Pull request by snowcall**
Allows to set a `rel=canonical` header containing a link to the original image, as described in
https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#rel-canonical-header-method

```
Link: <https://example.com/image.png>; rel="canonical"
```

### CODE REVIEW

**Comment by DarthSim** [comment]
Could you explain the purpose of this header sent for an image, please?

**Comment by snowcall** [comment]
When large networks and companies (think CDN providers, mobile frontend optimizers, and others) provide services such as lazy loading and image optimization, they often face concerns from site owners that these images are not associated with their website and may appear independently in search results. This is because the images are served from a domain like `imgproxy.another-company-cdn.com` and not from their websites.

Google explicitly stated in 2016 that `rel=canonical` headers are not used for images, but things started to change somewhere in 2019 when Google started supporting these headers for many media types (office documents, pdf, and others). These headers are now believed to be used to associate media with a canonical one when served from a different domain or has multiple versions:
```
https://example.com/image.png

https://example.com/image-300x300.png                   // duplicate
https://example.com/image-600x600.png                   // duplicate

https://imgproxy.some-cdn.com/<key>/<params>/<hash>     // duplicate
https://imgproxy.some-cdn.com/<key>/<params>/<hash>.jpg // duplicate
```

Site owners want to link (associate) all these optimized images with the original ones from their website and search engines now support this behaviour.

**Comment by DarthSim** [comment]
Well, this makes some sense to me. Please, add a couple of changes to the PR and I'll merge it:

1. Check that the source URL uses HTTP schema. Setting `s3://` or `local:///` URL as canonical is pretty senseless and may break your SEO instead of improving it. `strings.HasPrefix(url, "http://") || strings.HasPrefix(url, "https://")` should be just enough.
2. Add documentation for this config to the Server part of [configuration.md](https://github.com/imgproxy/imgproxy/blob/master/docs/configuration.md).

**Comment by snowcall** [comment]
Sorry for late response. Scheme checks and documentation are now added.

**Comment by snowcall** [comment]
@DarthSim is there anything else we should do?

**Comment by DarthSim** [comment]
It's all good. Thanks for the contribution!

**Pull request merged**
