### PR TITLE
Add IMGPROXY_IGNORE_ICCP config

### PR DESCRIPTION
**Pull request by MikeTangoEcho**
* Quickfix to temporary bypass buggy icc profiles (image darkens when converting PNG to JPEG, or add noise on resize)
* Can help providing *acceptable* images until they are fixed
* Nice enhancement would be to provide debug informations on ICC profiles

### CODE REVIEW

**Comment by DarthSim** [comment]
Hi,
Could you give me some of those "buggy" images?

**Comment by MikeTangoEcho** [comment]
**Context**: PNG with bad iccp -> JPEG with white background.

Here is the URL
`nosig/resize:fit:0:0:0:0/gravity:sm/quality:100/format:jpg/plain/...`

Here is the sample before
fail_iccpAdobeRGB1998

and after
fail_iccpAdobeRGB1998

Debug/Test on `alpine:latest`
* `apk add --update imagemagick --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main`
* `apk add --update vips-tools --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community`
* When using ImageMagick the background melt `convert fail_iccpAdobeRGB1998.png fail_iccpAdobeRGB1998.jpg` (Tested on alpine ` apk add --update imagemagick --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main`)
* When using  libvips tools, it looks ok `vips flatten fail_iccpAdobeRGB1998.png fail_iccpAdobeRGB1998.jpg[Q=100] --background 65535`.

```console
$ identify -verbose fail_iccpAdobeRGB1998.png
Image: fail_iccpAdobeRGB1998.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 2000x2000+0+0
  Resolution: 118.11x118.11
  Print size: 16.9334x16.9334
  Units: PixelsPerCentimeter
  Colorspace: sRGB
  Type: TrueColorAlpha
  Base type: Undefined
  Endianess: Undefined
  Depth: 16-bit
  Channel depth:
    Red: 16-bit
    Green: 16-bit
    Blue: 16-bit
    Alpha: 16-bit
  Channel statistics:
    Pixels: 4000000
    Red:
      min: 0  (0)
      max: 65535 (1)
      mean: 45546.6 (0.694997)
      standard deviation: 26890.6 (0.410324)
      kurtosis: -1.20747
      skewness: -0.801107
      entropy: 0.473194
    Green:
      min: 0  (0)
      max: 65535 (1)
      mean: 45880.1 (0.700086)
      standard deviation: 26474.9 (0.403981)
      kurtosis: -1.18471
      skewness: -0.809279
      entropy: 0.4756
    Blue:
      min: 0  (0)
      max: 65535 (1)
      mean: 47406.7 (0.72338)
      standard deviation: 25119.8 (0.383303)
      kurtosis: -0.901057
      skewness: -0.929791
      entropy: 0.482202
    Alpha:
      min: 0  (0)
      max: 65535 (1)
      mean: 24532 (0.374335)
      standard deviation: 31693.9 (0.483618)
      kurtosis: -1.72931
      skewness: 0.519248
      entropy: 0.0815453
  Image statistics:
    Overall:
      min: 0  (0)
      max: 65535 (1)
      mean: 40841.4 (0.6232)
      standard deviation: 27544.8 (0.420306)
      kurtosis: -1.65346
      skewness: -0.486233
      entropy: 0.378135
  Alpha: srgba(255,255,255,0)   #FFFFFFFFFFFF0000
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 2000x2000+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2019-06-25T13:35:20+00:00
    date:modify: 2019-06-25T13:17:42+00:00
    icc:copyright: Copyright 2000 Adobe Systems Incorporated
    icc:description: Adobe RGB (1998)
    png:iCCP: chunk was found
    png:IHDR.bit-depth-orig: 16
    png:IHDR.bit_depth: 16
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 2000, 2000
    png:pHYs: x_res=11811, y_res=11811, units=1
    signature: 1e203af0afd27462627da4d1cf9054bd025aecb62beed51752b50b44b496245d
  Profiles:
    Profile-icc: 560 bytes
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 5.27134MiB
  Number pixels: 4000000
  Pixels per second: 14.5661MP
  User time: 0.270u
  Elapsed time: 0:01.274
  Version: ImageMagick 7.0.8-49 Q16 x86_64 2019-06-17 https://imagemagick.org
```

**Comment by DarthSim** [comment]
Well, the image isn't buggy at all; this is an imgproxy's issue. The fix will come to the repo today. Thanks a lot for the sample, it really helped me.

**Comment by DarthSim** [comment]
`darthsim/imgproxy:latest` includes the fix. Please try it out

**Comment by MikeTangoEcho** [comment]
Hi, i ran some samples and its looks ok, great work! We will run further tests later and wait for a release.

By the way where did you get the cmyk profile stored as base64 in [cmyk_profile.go] ?(https://raw.githubusercontent.com/imgproxy/imgproxy/master/cmyk_profile.go)

I will close the PR later.

**Comment by DarthSim** [comment]
I don't remember, it was like a year ago :) It's some kind of "standard" CMYK profile. I'm going to remove it from imgproxy since libvips v8.8+ has built-in profiles.

**Comment by MikeTangoEcho** [comment]
We are still doing tests, i will close the PR since i didn't find problems until now.
Thank you.

**Pull request closed without merging**
