### PR TITLE
Support arithmetic encoded jpeg files

### PR DESCRIPTION
**Pull request by joec4i**
At the moment, imgproxy throws the following error for JPEG files encoded with arithmetic coding.
```
Can't download source image: invalid JPEG format: missing SOF marker
```

Since artithmetic coding is supported by the current version of libjpeg-turbo and vips has no problem processing files encoded with it, I think it can be supported by imgproxy too.
```
root@3f21642207d3:/data# vipsthumbnail test1.arith.jpg -o test.jpg -s 20
root@3f21642207d3:/data# file test1.arith.jpg
test1.arith.jpg: JPEG image data, JFIF standard 1.01, resolution (DPCM), density 28x28, segment length 16
root@3f21642207d3:/data# file test.jpg
test.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=3], baseline, precision 8, 20x20, components 1
```

This PR changes the supported range of SOF markers from `0xc0-0xc2` to ~~`0xc0-0xcf`~~ [all valid SOF markers](https://exiftool.org/TagNames/JPEG.html#SOF)
```
0x0 = Baseline DCT, Huffman coding
0x1 = Extended sequential DCT, Huffman coding
0x2 = Progressive DCT, Huffman coding
0x3 = Lossless, Huffman coding
0x5 = Sequential DCT, differential Huffman coding
0x6 = Progressive DCT, differential Huffman coding
0x7 = Lossless, Differential Huffman coding
0x9 = Extended sequential DCT, arithmetic coding
0xa = Progressive DCT, arithmetic coding
0xb = Lossless, arithmetic coding
0xd = Sequential DCT, differential arithmetic coding
0xe = Progressive DCT, differential arithmetic coding
0xf = Lossless, differential arithmetic coding
```

Please review! Thanks 🙏

### CODE REVIEW

**Comment by joec4i** [comment]
Hmm. The implementation is not right. Closing this for now. I'll open a new one once I have a closer look.

**Comment by DarthSim** [comment]
Hi @joec4i!

This does look correct to me. What doe not look right to you?

**Comment by joec4i** [comment]
Hi @DarthSim . I forgot to exclude the 3 non-SOF markers that are between `0xc0` and `0xcf` 
```
	jpegDhtMarker   = 0xc4 // Define Huffman Table
	jpegJpgMarker   = 0xc8 // JPEG Extensions
	jpegDacMarker   = 0xcc // Define Arithmetic Coding
```
The following error could occur to jpeg files with a DHT Marker:
```
Can't download source image: invalid JPEG format: unsupported precision        
```

It's fixed now though.  Please have another look. Thanks!

**Comment by joec4i** [comment]
Hi @DarthSim . I squeezed in a refactoring PR to remove the special treatment for the three markers. It's ready for review now. Cheers!

**Comment by DarthSim** [comment]
Merged! Thanks again for your contribution!

**Pull request merged**
